version: '2'
services:
    geodocker-zookeeper:
        image: daunnc/geodocker-zookeeper:latest
        #  volumes:
        #   - '/data/gt/hdfs:/data/hdfs'
    geodocker-hadoop-name:
        image: daunnc/geodocker-hadoop:latest
        command: name dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        ports:
          - 50070:50070
        # volumes:
        #   - '/data/gt/hdfs:/data/hdfs'
        depends_on:
          - geodocker-zookeeper
    geodocker-hadoop-sname:
        image: daunnc/geodocker-hadoop:latest
        command: sname dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #  - '/data/gt/hdfs:/data/hdfs'
        depends_on:
          - geodocker-hadoop-name
    geodocker-hadoop-data:
        image: daunnc/geodocker-hadoop:latest
        command: data dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
        # volumes:
        #  - '/data/gt/hdfs:/data/hdfs'
        depends_on:
          - geodocker-hadoop-name
    geodocker-accumulo-master:
        image: daunnc/geodocker-accumulo:latest
        command: master dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
          INSTANCE_NAME: gis
        depends_on:
          - geodocker-hadoop-data
        #volumes:
        #  - './accumulo/fs/sbin:/sbin:rw'
    geodocker-accumulo-gc:
        image: daunnc/geodocker-accumulo:latest
        command: gc dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-monitor:
        image: daunnc/geodocker-accumulo:latest
        command: monitor dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        ports:
          - 50095:50095
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-tracer:
        image: daunnc/geodocker-accumulo:latest
        command: tracer dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on:
          - geodocker-accumulo-master
    geodocker-accumulo-tserver:
        image: daunnc/geodocker-accumulo:latest
        command: tserver dev
        environment:
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          ACCUMULO_ZOOKEEPERS: geodocker-zookeeper
          ACCUMULO_SECRET: secret
          ACCUMULO_PASSWORD: GisPwd
        depends_on:
          - geodocker-accumulo-master
          - geodocker-accumulo-gc
          - geodocker-accumulo-monitor
          - geodocker-accumulo-tracer
    geodocker-spark-master:
        image: daunnc/geodocker-spark:latest
        command: master dev
        hostname: geodocker-spark-master
        environment:
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          MASTER: spark://geodocker-spark-master:7077
        ports:
          - 8080:8080
        # volumes:
        #  - '/data/gt/spark:/data/spark'
        depends_on:
          - geodocker-hadoop-data
    geodocker-spark-worker:
        image: daunnc/geodocker-spark:latest
        command: worker dev
        hostname: geodocker-spark-worker
        environment:
          SPARK_DAEMON_MEMORY: 2g
          SPARK_SUBMIT_DRIVER_MEMORY: 1g
          SPARK_WORKER_CORES: 8
          SPARK_WORKER_MEMORY: 16g
          HADOOP_MASTER_ADDRESS: geodocker-hadoop-name
          SPARK_MASTER: geodocker-spark-master
        depends_on:
          - geodocker-spark-master
    geodocker-geoserver:
        image: daunnc/geodocker-geoserver:latest
        hostname: geodocker-geoserver
        depends_on:
          - geodocker-accumulo-tserver
